### PR TITLE
optimize large slice alloc in Stats

### LINKED ISSUE #104: High Memory Usage with `ethtool.Stats` Function in Go 1.24+
#### Description:
We have observed a significant increase in memory churn when using the `ethtool.Stats` function with Go version 1.24 and onwards. This is due to a change in the Go compiler's memory allocation strategy, where objects larger than 128KB are now allocated on the heap instead of the stack. Previously, this threshold was in the range of MBs. 

As a result, every time the `Stats` function is called, large objects like `gstrings` and `stats` are allocated on the heap, leading to increased memory pressure and frequent garbage collection.

#### Steps to Reproduce:
1. Use Go 1.24 or newer.
2. Call the `ethtool.Stats` function in a program.

#### Observed Behavior:
- A large amount of memory is allocated on the heap for `gstrings` and `stats` variables during each call to `ethtool.Stats`.
- This memory is then left for the garbage collector to clean up, resulting in frequent garbage collection cycles and potential performance degradation.

#### Expected Behavior:
- Memory allocation behavior should be optimized to avoid excessive heap allocations for large local variables like `gstrings` and `stats`.
- A consistent and efficient allocation strategy should be implemented to minimize garbage collection overhead.

#### Reference:
This behavior is linked to changes in Go's escape analysis and memory allocation strategy introduced in Go 1.24. For more details, refer to the related Golang issue: [golang/go#73536](https://github.com/golang/go/issues/73536).

#### Analysis with pprof:
This issue can be easily analyzed using `pprof`. Below is a sample program that demonstrates the high memory churn:

```go
package main

import (
	"fmt"
	"log"
	"net"
	"time"

	"net/http"
	_ "net/http/pprof"

	"github.com/safchain/ethtool"
)

func main() {
	go func() {
		log.Println(http.ListenAndServe("localhost:8000", nil))
	}()

	ifs, err := net.Interfaces()
	if err != nil {
		log.Fatal(err)
	}
	if len(ifs) == 0 {
		log.Fatal("No interfaces found")
	}

	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			eth, err := ethtool.NewEthtool()
			if err != nil {
				log.Fatalf("Error creating ethtool: %v", err)
			}
			for _, iface := range ifs {
				stats, err := eth.Stats(iface.Name)
				if err != nil {
					log.Printf("Error getting stats for %s: %v", iface.Name, err)
					continue
				}
				fmt.Printf("Stats for %s: %+v\n", iface.Name, stats)
			}
			eth.Close()
		}
	}
}
```

Using `pprof` to analyze the heap, we can observe a significant difference in the `alloc_space` profile between Go versions 1.23 and 1.24. This confirms the issue with increased heap allocations in Go 1.24.

Thank you for addressing this!

### PR DESCRIPTION
**Pull request by halfcrazy**
fix #104

Introduce sync pool to optimize large object allocation

```
$ benchstat bench.out.master bench.out.perf
goos: linux
goarch: amd64
pkg: github.com/safchain/ethtool
cpu: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
               │ bench.out.master │            bench.out.perf            │
               │      sec/op      │    sec/op     vs base                │
Stats/enp0s3-4       789.0µ ± 11%   398.5µ ± 14%  -49.49% (p=0.002 n=10)
Stats/enp0s8-4       777.9µ ±  8%   373.7µ ±  7%  -51.96% (p=0.000 n=10)
geomean              783.4µ         385.9µ        -50.74%

               │ bench.out.master │            bench.out.perf             │
               │       B/op       │     B/op       vs base                │
Stats/enp0s3-4    1300.243Ki ± 0%   3.576Ki ± 30%  -99.72% (p=0.000 n=10)
Stats/enp0s8-4    1300.238Ki ± 0%   3.896Ki ± 11%  -99.70% (p=0.000 n=10)
geomean              1.270Mi        3.732Ki        -99.71%

               │ bench.out.master │           bench.out.perf           │
               │    allocs/op     │ allocs/op   vs base                │
Stats/enp0s3-4         59.00 ± 0%   51.00 ± 0%  -13.56% (p=0.000 n=10)
Stats/enp0s8-4         59.00 ± 0%   51.00 ± 0%  -13.56% (p=0.000 n=10)
geomean                59.00        51.00       -13.56%
```

### CODE REVIEW

File: ethtool.go [hunk 1]
```diff
@@ -109,6 +109,23 @@ const (
...
+		},
+	}
+	statsPool = sync.Pool{
+		New: func() interface{} {
+			// new() will allocate and zero-initialize the struct.
+			// The large data array within ethtoolStats will be zeroed.
+			return new(ethtoolStats)
+		},
+	}
+)
```
Comment (ritwikranjan) [inline ethtool.go:127]: Can we in addition to this give control to the customer to pass in the buffer? This implementation will be really good if someone wants a threadsafe operation however it will have overhead if you compare to a static one time buffer allocation.

**Comment by ritwikranjan** [comment]
This is the change i was planning: https://github.com/safchain/ethtool/pull/106, maybe we can combine the two of them. This change can be done as a default and then we would also expose those buffers for customers to have them manage those variables themselves.

**Comment by halfcrazy** [comment]
> This is the change i was planning: #106, maybe we can combine the two of them. This change can be done as a default and then we would also expose those buffers for customers to have them manage those variables themselves.

That's ok. The original `Stats` will use the in-tree buffer pool.

**Comment by ritwikranjan** [comment]
We can merge this anyway, I can rebase my changes on top of it, and we can look if it makes sense or not!
This definitely looks good to me.

**Review by anubhabMajumdar — APPROVED** [review]
Thanks for the fix!
